language: java
sudo: false

BUCKET_NAME=allure-poc-prjct-bucket
gsutil cp gs://${BUCKET_NAME}/* ./public/
ls ./public

script:
  - publishing.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: public
  repo:  uvidit/pocProjectDocPages
  target-branch: gh-pages


