language: java
sudo: false

script:
  - gsutil cp gs://allure-poc-prjct-bucket/* ./public/
  - bash ls ./public
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: public
  repo:  uvidit/pocProjectDocPages
  target-branch: gh-pages


